atom-material/atom-material-ui

styles/accent-colors.less
styles/tabs.less

The color of the modified close icon is now set to the configurable accent-color.
===
Fixed the positioning of the placeholder while dragging tabs. The placeholder color is now set to the configurable accent-color. The background of the tab being dragged is no longer transparent.

Enhancing tabs.

---

styles/overlays.less

The loading indicator that appears when indexing the project has no padding. I added in the default `@component-padding` (10px) to fix the appearance.

Adding space to loading indicator.

---

styles/tabs.less

There is a small visual artifact on the selected tab (see main.js in screenshot below) that appears when animations are disabled.
This update hides the ::before element completely.

Hide animation artifact on tab when animations are disabled

---

lib/config.coffee
lib/settings.coffee
styles/tabs.less

Not the most elegant configuration file, I think, but it works well. Resolves #53.
GIFs:

Add support for icons on all tabs

---

styles/progress.less

The animation of the `<progress>` element can make the CPU spike a bit, this PR:
- Limits the buffering animation to only 30s, see https://github.com/atom/atom/issues/6646#issuecomment-130350092
- Adds a `-webkit-` prefix to properly remove the animation, see issue https://github.com/atom/atom-dark-ui/pull/49

Limit CPU usage of <progress> elements

---

styles/tooltips.less
styles/ui-variables.less

The specs say it has to be in Grey 700 background, white text, 22px in height, 14px from the element, 0.9 opacity, and no arrows. Digging Polymer results in a 0.5s opacity transition with the default timing cubic-bezier.
I added `@md-grey-700` for the color and `@md-timing-function` for the timing. Because of how the tooltips get deleted I can't add the fadeout transition. Also the 14px margin from the element gets applied to top and bottom tooltips only — the left and right tooltip margins is kept intact since there's no docs on left and right tooltip margins (also top, but it's quite similar with the bottom counterpart).
Here's a GIF.

Tooltips closer to the Material Design specs

---

index.less
styles/jumpy.less

[Jumpy](//atom.io/packages/jumpy)
Before:
After:
This problem that is peculiar to the theme.

Fix invisible labels of jumpy

---

styles/tree-view.less

This fixes an issue I noticed under linux in which the scroll bar for the tree view does not render correctly.
To reproduce the problem:
* open atom in a directory with enough files to make the vertical scrollbar appear
* make sure that a sorce file is open in the text editor (the problem does not occur when viewing the initial screen or the settings tab)
* scroll the tree view up or down
I can see this problem occurring in Linux Mint and Ubuntu. It looks ok under Windows, while I haven't tried on Mac. It also seems to happen with any syntax theme while using atom-material-ui.
Below is an animation showing the problem:
This is probably the same problem as issue #104.

Fix problem with tree view scrollbar rendering incorrectly

---

styles/accent-colors.less
styles/tabs.less

Easier to recognize what modified files haven't been saved.
The faded white circle was hard to catch at a glance, especially if you had too many tabs open.

Make the modified file indicator easier to recognize for inactive tabs

---

styles/tabs.less

Looks like the line border: 2px solid @tab-border-color; was removed in another one of your commits.
When a modified tab was inactive the modified file indicator was not visible.
After most recent update:
Should look like this:

Modified file indicator not showing up properly on inactive tabs

---

styles/tool-bar.less

I refactored the styles to remove duplication of definitions. Also
manually defined the icon size regardless of the setting chosen for the
tool-bar package. This should eventually be configured via a UI scaling
option in the material-ui settings.
I seem to have broken the toolbar when in the top position so that will
need to be looked at at some point and fixed.
The hover color of the buttons also needs to be defined correctly. I
wasn't sure whether it should be defined here or if there was a global
definition for button styles somewhere which would be more appropriate.

Removed redundant styles and normalized icon size of tool-bar.

---

styles/tree-view.less

This PR fades out the ignored directories and files (e.g. node_modules) in the tree view.
I think this was the previous behavior before v1.0.0
Fixes: https://github.com/silvestreh/atom-material-ui/issues/150

Fix: fade out ignored directories and files in the tree view

---

styles/editor.less

The previous value of `0.8rem` made the characters looks too small
in comparison with the input's height.
The change, albeit subtle, provides a clearer look and visual
confort without compromising line length or looking disproportional.
Fix #166

Tweak the text input font size

---

styles/packages/tool-bar.less

Fixed first button same background color as tab bar on vertical tool bar with new item [aligned to the end](https://github.com/suda/tool-bar/pull/110) feature. This was part of the recently released version of [Tool Bar](https://atom.io/packages/tool-bar) package.
| Before | After |
| --- | --- |
| ![tool-bar-before](https://cloud.githubusercontent.com/assets/55841/13548521/8c5646d8-e2f2-11e5-8783-58a8098a12a8.png) | ![tool-bar-after](https://cloud.githubusercontent.com/assets/55841/13548525/99a5eb7c-e2f2-11e5-9dd1-60bdc1a1f31b.png)  |

Fixed first button same background color as tab bar on vertical tool bar 

---

styles/packages/build.less

I've made some quick fixes to make the new version of Atom Build work. It's not great, but it's something:
It works okayish with the current version, so coordinated releases should not be required.
What do you think?
Fixes #240

Make compatible with next version of Atom Build

---

styles/packages/linter.less

A `#linter-inline > linter-message` can have an expando-arrow on it. this theme’s style doesn’t allow it to expand as of now.
makings its height to flexible using `min-height` instead of `height` fixes that

Make linter-message use min-height

---

styles/settings/inputs.less

There's a glitch on the settings page without the adding the float.
**Before**:
**After**:

Add float for checkboxes & radiobuttons

---

styles/text.less

This rule selector applies bold font to **any** element using the "highlight" word in its classes, causing visualization problems. E.g. the atom-trailing-spaces package.

Too general selector removed from rule

---

lib/config-schema.json
lib/settings.js
spec/settings-tabs-spec.js
styles/custom.less
styles/tabs.less

This provides a toggleable solution to #229.

Add toggleable tab min- and max-width

---

styles/markdown-preview.less

I had reported a bug #340 about incorrect style in [markdown-preview](https://github.com/atom/markdown-preview).
**Screenshots**
^ error style with atom-material-ui theme
^ forcing font-size to be 80%
With unknown reason, the font-size of small tag in markdown-preview is set to 125%. This PR forces it to be 80%.

Force font-size of small tag to be 80% in markdown-preview.

---

styles/tabs.less

This theme [currently overrides](https://github.com/atom-material/atom-material-ui/blob/09d4be0e6da341f35cecc730b412d741dfa2cc80/styles/tabs.less#L188) the colour of tab-icons to make them more visible when viewed against a tinted background. As @silvestreh [explains](https://github.com/atom-material/atom-material-ui/issues/349#issuecomment-279673250), *"if you have a green icon with a green background you wouldn't see it."*
Although well-intentioned, this solution breaks two user expectations:
* __The `enableVcsColoring` setting of the core `tabs` package is ignored.__
It's likely (and logical) that a tab's icon share the colour applied to its label. When VCS-aware tabs are enabled, the label's colour is rendered in orange or green for changed and added files, respectively. However, …

Preserve colour of tab-icons

---

styles/text.less

While using this theme with a light syntax I noticed that some text (the highlights) in the Timecop panel was difficult to read (specially the green and yellow ones). 
This PR lower the fadeout of the background and increase the lighten in the text color for better contrast in them.
So it now looks like this:
The highlights can be read easily.

Fix highlight-* colors

---

styles/packages/main.less
styles/packages/vim-mode-plus.less

When "Paint text editor's cursor" option is on, `vim-mode-plus` cursor will inherit the theme's primary color as it does in the insert mode. 
The cursor color in different modes will finally be consistent. It'll just work™
Insert Mode:
Normal Mode:
Pending Operator Mode:
Surrounding Mode:
Users who defined their own styles could potentially be impacted.
#453

add a `vim-mode-plus` modal cursor color override

---

styles/packages/activate-power-mode.less
styles/packages/main.less

It makes the combo counter from the [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package gets the color from this theme.
The original combo looks like this:
with a fixed green color, and while getting a higher level it changes the color.
With this change the combo now looks depending on the selected color:
and the color change for higher levels is more subtle.

Add support for the activate-power-mode package.

---

lib/main.js
lib/tab-bar/index.js
package.json
styles/tabs.less

Adds an option to make the tabs stretch to full available width of the tab bar. This follows what the One Dark theme does, for example.
- Visual pleasure 😍
- None - the change is configurable and off by default
Closes #445.

Add option to stretch tabs to full tab width
